language: node_js
node_js:
- '10'
cache: npm
script:
- fjpublish env test -y
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_0fe5cf04ebe9_key -iv $encrypted_0fe5cf04ebe9_iv
  -in .travis.env -out pushConfig.js -d
